import { listenTo, type UnlistenFn } from '@platform/services/events.service';
import type { MainRoot } from '@store/roots/main-root';
import type { InputButtonEvent, InputDevice } from '@/types/bindings';
import {
  INPUT_BUTTON_EVENT,
  INPUT_DEVICES_EVENT,
} from '@platform/sync/sim-events';

/**
 * The device list and the last button pressed, for the settings screen that
 * captures a binding. The edges themselves are dispatched by the backend,
 * which reads the wheel; this window only shows them.
 */
export const setupDeviceBindings = async (
  root: MainRoot
): Promise<UnlistenFn[]> => {
  const unlistens: UnlistenFn[] = [];

  unlistens.push(
    await listenTo<InputDevice[]>(INPUT_DEVICES_EVENT, () => {
      // The hot-plug event only says "something changed"; the reconcile round
      // trip is what carries the offline entries and the id rewrites.
      void reconcileDevices(root);
    })
  );

  unlistens.push(
    await listenTo<InputButtonEvent>(INPUT_BUTTON_EVENT, (event) => {
      root.deviceInput.setLastEvent(event.payload);
    })
  );

  await reconcileDevices(root);

  return unlistens;
};

/**
 * A device whose GUID was regenerated by a driver reinstall keeps its bindings:
 * the backend matches it by vendor/product and the stored id is rewritten here,
 * so the fallback is used at most once.
 */
const reconcileDevices = async (root: MainRoot) => {
  const remaps = await root.deviceInput.resolveDevices(
    root.bindings.referencedDeviceIds
  );

  for (const remap of remaps) {
    root.bindings.rewriteDeviceId(remap.previousId, remap.nextId);
  }
};
