import { listenTo, type UnlistenFn } from '@platform/services/events.service';
import type { RootStore } from '@store/root-store';
import type { InputButtonEvent, InputDevice } from '@/types/bindings';
import {
  INPUT_BUTTON_EVENT,
  INPUT_DEVICES_EVENT,
} from '@platform/sync/sim-events';
import { applyKeyboardBindings, dispatchDeviceButton } from './binding-runner';

/**
 * Main-window only, like the keyboard registrations: a second window would
 * dispatch every action twice. Overlays are reached through the existing
 * `emitToOverlays` helpers inside the actions themselves.
 */
export const setupDeviceBindings = async (
  root: RootStore
): Promise<UnlistenFn[]> => {
  const unlistens: UnlistenFn[] = [];

  unlistens.push(
    await listenTo<InputDevice[]>(INPUT_DEVICES_EVENT, () => {
      // The hot-plug event only says "something changed"; the reconcile round
      // trip is what carries the offline entries and the id rewrites.
      void reconcileDevices(root);
    })
  );

  unlistens.push(
    await listenTo<InputButtonEvent>(INPUT_BUTTON_EVENT, (event) => {
      root.deviceInput.setLastEvent(event.payload);

      dispatchDeviceButton(
        root,
        event.payload.deviceId,
        event.payload.button,
        event.payload.pressed
      );
    })
  );

  await reconcileDevices(root);

  return unlistens;
};

/**
 * A device whose GUID was regenerated by a driver reinstall keeps its bindings:
 * the backend matches it by vendor/product and the stored id is rewritten here,
 * so the fallback is used at most once.
 */
const reconcileDevices = async (root: RootStore) => {
  const remaps = await root.deviceInput.resolveDevices(
    root.bindings.referencedDeviceIds
  );

  for (const remap of remaps) {
    root.bindings.rewriteDeviceId(remap.previousId, remap.nextId);
  }
};

export const reapplyBindings = (root: RootStore) => applyKeyboardBindings(root);
