import { TelemetryDebugWidgetContainer } from '../components/widgets/TelemetryDebugWidget/TelemetryDebugWidgetContainer';
import { SpeedWidget } from '../components/widgets/SpeedWidget/SpeedWidget';
import { InputTraceWidgetContainer } from '../components/widgets/InputTraceWidget/InputTraceWidgetContainer';
import { ProximityRadarWidgetContainer } from '../components/widgets/ProximityRadarWidget/ProximityRadarWidgetContainer';
import { RadarBarWidgetContainer } from '../components/widgets/RadarBarWidget/RadarBarWidgetContainer';
import { StandingsWidgetContainer } from '../components/widgets/StandingsWidget/StandingsWidgetContainer';
import { RelativeWidgetContainer } from '../components/widgets/RelativeWidget/RelativeWidgetContainer';
import { TrackMapWidgetContainer } from '../components/widgets/TrackMapWidget/TrackMapWidgetContainer';
import { RelativeMapWidgetContainer } from '../components/widgets/RelativeMapWidget/RelativeMapWidgetContainer';
import { LedFlagWidgetContainer } from '../components/widgets/LedFlagWidget/LedFlagWidgetContainer';
import { ChassisWidgetContainer } from '../components/widgets/ChassisWidget/ChassisWidgetContainer';
import { LapDeltaWidgetContainer } from '../components/widgets/LapDeltaWidget/LapDeltaWidgetContainer';
import { LapTimesWidgetContainer } from '../components/widgets/LapTimesWidget/LapTimesWidgetContainer';
import { TimerWidgetContainer } from '../components/widgets/TimerWidget/TimerWidgetContainer';
import { WeatherWidgetContainer } from '../components/widgets/WeatherWidget/WeatherWidgetContainer';
import { FuelWidgetContainer } from '../components/widgets/FuelWidget/FuelWidgetContainer';
import { FlatFlagsWidgetContainer } from '../components/widgets/FlatFlagsWidget/FlatFlagsWidgetContainer';
import { GMeterWidgetContainer } from '../components/widgets/GMeterWidget/GMeterWidgetContainer';
import type {
  WidgetConfig,
  WidgetDefaultConfig,
} from '../types/widget-settings';

export const LAP_TIMES_DEFAULT_WIDTHS: Record<string, number> = {
  vertical: 230,
  horizontal: 1130,
};

export const LAP_DELTA_DEFAULT_WIDTHS: Record<string, number> = {
  vertical: 230,
  horizontal: 900,
};

export const LINEAR_MAP_SIZES: Record<
  string,
  { designWidth: number; designHeight: number }
> = {
  horizontal: { designWidth: 400, designHeight: 40 },
  vertical: { designWidth: 40, designHeight: 400 },
};

export const INPUT_TRACE_SIZES: Record<
  string,
  { designWidth: number; designHeight: number }
> = {
  horizontal: { designWidth: 400, designHeight: 220 },
  vertical: { designWidth: 400, designHeight: 110 },
};

export const WIDGETS: WidgetConfig[] = [
  {
    id: 'speed',
    label: 'Speed',
    description: 'Speedometer with gear and RPM indicator.',
    component: SpeedWidget,
    enabled: true,
    x: 400,
    y: 100,
    currentWidth: 500,
    currentHeight: 120,
    designWidth: 500,
    designHeight: 120,
    backgroundColor: '#252525',
    backgroundColorEdge: '#14141b',
    borderColor: 'rgba(255, 255, 255, 0.1)',
    hotkey: 'F10',
    widgetSpecificSettings: {
      rpmColorTheme: 'custom',
      rpmColorLow: '#22c55e',
      rpmColorMid: '#fbbf24',
      rpmColorHigh: '#ef4444',
      rpmColorShift: '#a855f7',
      rpmColorLimit: '#ff4d00',
      showRpmBar: true,
      showTemps: true,
      showRpmColor: true,
      pitSpeedLimitOverride: null,
      gearColor: '#fbbf24',
      gearPanelBg: 'rgba(255,255,255,0.05)',
      ledShape: 'square',
    },
  },
  {
    id: 'input-trace',
    label: 'Input Trace',
    description: 'Live throttle, brake, and clutch inputs.',
    component: InputTraceWidgetContainer,
    enabled: false,
    x: 400,
    y: 300,
    currentWidth: 400,
    currentHeight: 220,
    designWidth: 400,
    designHeight: 220,
    backgroundColor: '#252525',
    backgroundColorEdge: '#14141b',
    borderColor: 'rgba(255, 255, 255, 0.1)',
    hotkey: 'F11',
    widgetSpecificSettings: {
      showThrottle: true,
      showBrake: true,
      showClutch: true,
      throttleColor: '#00ff00',
      brakeColor: '#ff3333',
      clutchColor: '#3399ff',
      barMode: 'horizontal',
      historySeconds: 5,
      lineWidth: 3.5,
      smoothing: 0,
    },
  },
  {
    id: 'proximity-radar',
    label: 'Proximity Radar',
    description: 'Visual radar for nearby traffic.',
    component: ProximityRadarWidgetContainer,
    enabled: false,
    x: 600,
    y: 300,
    currentWidth: 200,
    currentHeight: 300,
    designWidth: 200,
    designHeight: 300,
    backgroundColor: 'transparent',
    backgroundColorEdge: 'transparent',
    borderColor: 'transparent',
    hotkey: 'F6',
    widgetSpecificSettings: {
      visibilityMode: 'proximity',
      proximityThreshold: 5,
      hideDelay: 2,
    },
  },
  {
    id: 'radar-bar',
    label: 'Radar Bar',
    description: 'Full-width side proximity indicators.',
    component: RadarBarWidgetContainer,
    enabled: false,
    x: 200,
    y: 300,
    currentWidth: 800,
    currentHeight: 380,
    designWidth: 800,
    designHeight: 380,
    backgroundColor: 'transparent',
    backgroundColorEdge: 'transparent',
    borderColor: 'transparent',
    hotkey: 'F7',
    widgetSpecificSettings: {
      visibilityMode: 'proximity',
      proximityThreshold: 3,
      hideDelay: 2,
      barDisplayMode: 'both',
    },
  },
  {
    id: 'standings',
    label: 'Standings',
    description: 'Live session standings and intervals.',
    component: StandingsWidgetContainer,
    enabled: false,
    x: 50,
    y: 50,
    currentWidth: 640,
    currentHeight: 450,
    designWidth: 900,
    designHeight: 450,
    backgroundColor: '#252525',
    backgroundColorEdge: '#14141b',
    borderColor: 'rgba(255, 255, 255, 0.1)',
    hotkey: 'F3',
    widgetSpecificSettings: {
      enableClassCycling: false,
      classCyclingToggleHotkey: '',
      classPrevHotkey: '',
      classNextHotkey: '',
      showPosChange: true,
      showColumnHeaders: true,
      showSessionHeader: true,
      showWeather: true,
      showSOF: true,
      showTotalDrivers: true,
      showBrand: true,
      showTire: true,
      showIRatingBadge: true,
      showClassBadge: true,
      showIrChange: false,
      showPitStops: true,
      showLapsCompleted: false,
      showIncidentsBadge: true,
      abbreviateNames: false,
    },
  },
  {
    id: 'relative',
    label: 'Relative',
    description: 'Gaps to cars ahead and behind you.',
    component: RelativeWidgetContainer,
    enabled: false,
    x: 50,
    y: 300,
    currentWidth: 420,
    currentHeight: 400,
    designWidth: 420,
    designHeight: 400,
    backgroundColor: '#252525',
    backgroundColorEdge: '#14141b',
    borderColor: 'rgba(255, 255, 255, 0.1)',
    hotkey: 'F4',
    widgetSpecificSettings: {
      showIRatingBadge: true,
      showClassBadge: true,
      showPitIndicator: true,
      abbreviateNames: true,
      showTrendIcon: true,
    },
  },
  {
    id: 'track-map',
    label: 'Track Map',
    description: 'Dynamic 2D map of the current circuit.',
    component: TrackMapWidgetContainer,
    enabled: false,
    x: 800,
    y: 50,
    currentWidth: 400,
    currentHeight: 400,
    designWidth: 400,
    designHeight: 400,
    backgroundColor: 'transparent',
    backgroundColorEdge: 'transparent',
    borderColor: 'transparent',
    hotkey: 'F5',
    widgetSpecificSettings: {
      showLegend: true,
      legendPosition: 'right',
      showSectors: true,
      showSectorTimes: true,
      showSectorsOnMap: true,
      rotationMode: 'fixed',
      playerDotColor: '#ffffff',
      showPlayerLabel: true,
      leaderLabelMode: 'all',
      trackStrokePx: 10,
      trackBorderPx: 3,
      sectorStrokePx: 6,
      targetDotRadiusPx: 10,
    },
  },
  {
    id: 'relative-map',
    label: 'Relative Map',
    description: 'Progress bar of car track positions.',
    component: RelativeMapWidgetContainer,
    enabled: false,
    x: 50,
    y: 820,
    currentWidth: 400,
    currentHeight: 40,
    designWidth: 400,
    designHeight: 40,
    backgroundColor: '#252525',
    backgroundColorEdge: '#14141b',
    borderColor: 'rgba(255, 255, 255, 0.1)',
    hotkey: '',
    widgetSpecificSettings: {
      orientation: 'horizontal',
      playerDotColor: '#ffffff',
      targetDotRadiusPx: 10,
    },
  },
  {
    id: 'led-flags',
    label: 'LED Flags',
    description: 'LED matrix display of track flags.',
    component: LedFlagWidgetContainer,
    enabled: false,
    x: 760,
    y: 0,
    currentWidth: 232,
    currentHeight: 232,
    designWidth: 232,
    designHeight: 232,
    backgroundColor: 'transparent',
    backgroundColorEdge: 'transparent',
    borderColor: 'transparent',
    hotkey: '',
    widgetSpecificSettings: { alwaysShow: true, holdDuration: 3 },
  },
  {
    id: 'flat-flags',
    label: 'Flat Flags',
    description: 'Banner-style list of active track flags.',
    component: FlatFlagsWidgetContainer,
    autoHeight: true,
    enabled: false,
    x: 760,
    y: 250,
    currentWidth: 280,
    currentHeight: 160,
    designWidth: 280,
    designHeight: 160,
    backgroundColor: 'transparent',
    backgroundColorEdge: 'transparent',
    borderColor: 'transparent',
    hotkey: '',
    widgetSpecificSettings: { alwaysShow: true, holdDuration: 3 },
  },
  {
    id: 'chassis',
    label: 'Chassis',
    description: 'Tire pressures and brake temperatures.',
    component: ChassisWidgetContainer,
    enabled: false,
    x: 100,
    y: 100,
    currentWidth: 460,
    currentHeight: 320,
    designWidth: 460,
    designHeight: 320,
    backgroundColor: '#252525',
    backgroundColorEdge: '#14141b',
    borderColor: 'rgba(255, 255, 255, 0.1)',
    hotkey: '',
    widgetSpecificSettings: {
      showInboard: false,
    },
  },
  {
    id: 'example',
    label: 'Telemetry Debug',
    description: 'Raw telemetry data debugger.',
    component: TelemetryDebugWidgetContainer,
    enabled: false,
    x: 100,
    y: 100,
    currentWidth: 400,
    currentHeight: 700,
    designWidth: 400,
    designHeight: 700,
    backgroundColor: '#252525',
    backgroundColorEdge: '#14141b',
    borderColor: 'rgba(255, 255, 255, 0.1)',
    hotkey: 'F8',
  },
  {
    id: 'lap-delta',
    label: 'Lap Delta',
    description: 'Live delta against your best lap time.',
    component: LapDeltaWidgetContainer,
    autoHeight: true,
    enabled: false,
    x: 400,
    y: 200,
    currentWidth: 230,
    currentHeight: 180,
    designWidth: 230,
    designHeight: 180,
    backgroundColor: '#252525',
    backgroundColorEdge: '#14141b',
    borderColor: 'rgba(255, 255, 255, 0.1)',
    hotkey: '',
    widgetSpecificSettings: {
      layout: 'vertical',
      showSectorTimes: true,
      reference: 'session_best',
    },
  },
  {
    id: 'lap-times',
    label: 'Lap Times',
    description: 'Detailed history of your lap times.',
    component: LapTimesWidgetContainer,
    autoHeight: true,
    enabled: false,
    x: 400,
    y: 300,
    currentWidth: 230,
    currentHeight: 104,
    designWidth: 230,
    designHeight: 104,
    backgroundColor: '#252525',
    backgroundColorEdge: '#14141b',
    borderColor: 'rgba(255, 255, 255, 0.1)',
    hotkey: '',
    widgetSpecificSettings: {
      showLastLap: true,
      showBestLap: true,
      showP1: true,
      showPredicted: true,
      layout: 'vertical',
    },
  },
  {
    id: 'timer',
    label: 'Timer',
    description: 'Stint and total session timers.',
    component: TimerWidgetContainer,
    enabled: false,
    x: 50,
    y: 310,
    currentWidth: 240,
    currentHeight: 120,
    designWidth: 240,
    designHeight: 120,
    backgroundColor: '#252525',
    backgroundColorEdge: '#14141b',
    borderColor: 'rgba(255, 255, 255, 0.1)',
    hotkey: '',
    widgetSpecificSettings: {
      showFlag: true,
      showLaps: true,
      showPosition: true,
      showWallClock: true,
      showSimTime: true,
      showPcDate: false,
      showSimDate: true,
    },
  },
  {
    id: 'weather',
    label: 'Weather',
    description: 'Track conditions and wind information.',
    component: WeatherWidgetContainer,
    enabled: false,
    x: 760,
    y: 200,
    currentWidth: 240,
    currentHeight: 280,
    designWidth: 240,
    designHeight: 280,
    backgroundColor: '#252525',
    backgroundColorEdge: '#14141b',
    borderColor: 'rgba(255, 255, 255, 0.1)',
    hotkey: '',
    widgetSpecificSettings: {
      showCompass: true,
      showAirTemp: true,
      showTrackTemp: true,
      showWind: true,
      showHumidity: true,
      showForecast: true,
    },
  },
  {
    id: 'fuel',
    label: 'Fuel',
    description: 'Fuel level and consumption calculator.',
    component: FuelWidgetContainer,
    autoHeight: true,
    enabled: false,
    x: 760,
    y: 500,
    currentWidth: 240,
    currentHeight: 360,
    designWidth: 240,
    designHeight: 360,
    backgroundColor: '#252525',
    backgroundColorEdge: '#14141b',
    borderColor: 'rgba(255, 255, 255, 0.1)',
    hotkey: '',
    widgetSpecificSettings: {
      showChart: false,
      pitWarningLaps: 3,
      chartType: 'bar',
      barWidth: 5,
    },
  },
  {
    id: 'g-meter',
    label: 'G-Meter',
    description: 'Lateral and longitudinal G-force friction circle.',
    component: GMeterWidgetContainer,
    enabled: true,
    x: 100,
    y: 100,
    currentWidth: 240,
    currentHeight: 280,
    designWidth: 240,
    designHeight: 280,
    backgroundColor: '#252525',
    backgroundColorEdge: '#14141b',
    borderColor: 'rgba(255, 255, 255, 0.1)',
    hotkey: '',
    widgetSpecificSettings: {
      displayMode: 'fading',
      scale: 4,
      colorMode: 'advanced',
    },
  },
];

export const WIDGET_BY_ID = new Map(
  WIDGETS.map((widgetConfig) => [widgetConfig.id, widgetConfig])
);

export const DEFAULT_WIDGETS: WidgetDefaultConfig[] = WIDGETS.map(
  (currentWidget) => {
    const allowedEntries = Object.entries(currentWidget).filter(([key]) => {
      return key !== 'component' && key !== 'autoHeight';
    });

    return Object.fromEntries(allowedEntries) as WidgetDefaultConfig;
  }
);
