import type { WidgetManifest } from '@/types/widget-settings';
import {
  COMMON_WIDGET_DEFAULTS,
  TRANSPARENT_APPEARANCE_DEFAULTS,
} from '@ui/widgets/widget-manifest';

export const TRACK_MAP_MANIFEST: WidgetManifest = {
  id: 'track-map',
  telemetryEvents: ['carPositions'],
  label: 'Track Map',
  description: 'Dynamic 2D map of the current circuit.',
  requiredCapabilities: ['playerDynamics'],
  designWidth: 400,
  designHeight: 400,
  userSettings: {
    enabled: false,
    x: 800,
    y: 50,
    currentWidth: 400,
    currentHeight: 400,
    ...COMMON_WIDGET_DEFAULTS,
    ...TRANSPARENT_APPEARANCE_DEFAULTS,
    showSectors: true,
    showSectorsOnMap: true,
    rotationMode: 'fixed',
    playerDotColor: '#18181b',
    showPlayerLabel: true,
    leaderLabelMode: 'all',
    useLivePositions: true,
    trackStrokePx: 10,
    trackBorderPx: 3,
    sectorStrokePx: 6,
    targetDotRadiusPx: 10,
    showStartFinish: true,
    paceCarUseClassColor: false,
    paceCarColor: '#facc15',
    paceCarRadiusPx: 10,
    paceCarShowInPits: false,
    zoomEnabled: false,
    zoomLevel: 3,
    zoomRotate: false,
    classShapes: false,
    qualifyingVisibility: 'always',
  },
};
