//! Companion applications: the other programs a sim rig needs running.
//!
//! The contract is deliberately path-shaped. A companion is identified by the
//! executable the user pointed at, not by a name we invented — two builds of
//! the same tool in two folders are two entries, and a renamed folder is a
//! missing entry rather than a silently wrong one.

use serde::{Deserialize, Serialize};

/// One configured program, as the settings file stores it.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "dev", derive(specta::Type))]
#[serde(rename_all = "camelCase")]
pub struct CompanionApp {
    /// Stable id generated by the frontend when the entry is added.
    pub id: String,
    /// What the user sees. Seeded from the file name or the detection catalog.
    pub name: String,
    /// Absolute path to the executable.
    pub path: String,
    /// Command line passed on launch, split on spaces. Usually empty.
    pub args: String,
    /// Start it when Marble Trace starts, if it is not already running.
    pub launch_with_app: bool,
    /// Close it when Marble Trace closes — only ever the instance we started.
    pub close_with_app: bool,
    /// The executable to look for in the process list, when it is not the
    /// one that gets launched. Discord is started through its updater and
    /// runs as `Discord.exe` out of a versioned folder, so matching the
    /// launched file would report it as never running.
    #[serde(default)]
    pub process_name: Option<String>,
}

/// A program the catalog scan found installed on this machine.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "dev", derive(specta::Type))]
#[serde(rename_all = "camelCase")]
pub struct DetectedApp {
    pub name: String,
    pub path: String,
    /// Command line the program needs to start properly, empty for most.
    pub args: String,
    /// The executable to look for in the process list, when it is not the
    /// one that gets launched. Discord is started through its updater and
    /// runs as `Discord.exe` out of a versioned folder, so matching the
    /// launched file would report it as never running.
    #[serde(default)]
    pub process_name: Option<String>,
}

/// Live state of one configured program.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[cfg_attr(feature = "dev", derive(specta::Type))]
#[serde(rename_all = "camelCase")]
pub struct CompanionStatus {
    pub id: String,
    pub running: bool,
    /// True while the running instance is the one this app started, which is
    /// the only instance it is allowed to close.
    pub owned: bool,
    /// False when the executable is no longer where the entry says it is.
    pub exists: bool,
}
