//! The bindable actions, declared once, and the shapes the hotkey dispatcher
//! takes from and gives to the frontend.
//!
//! The list is a value, not a type: the settings window needs every id, label
//! and default binding as a literal, and the dispatcher needs to know what each
//! one does. Both read [`HOTKEY_ACTIONS`] — the frontend through the file
//! [`export_hotkey_actions`] writes. Adding an action is one entry here and
//! its label under `bindings.actions` in `main-app.json`.
//!
//! What an action *does* is its [`HotkeyEffect`], and the effect decides the
//! kind the frontend sees:
//!
//! - **sim** — acts on the car through the telemetry thread. Passes the layout
//!   gate and nothing else.
//! - **view** — a control message to the windows and remote screens that draw
//!   the widget, or the overlay's own drag and interact modes. Each client
//!   picks the instances marked for hotkeys itself.
//! - **settings** — writes settings, which the main window owns. The dispatcher
//!   catches the key and hands the action to main, which applies it.

// The labels, kinds and defaults are read only by the `dev` exporter that
// writes them out for the frontend; a release build would flag them unused.
#![cfg_attr(not(feature = "dev"), allow(dead_code))]

use serde::{Deserialize, Serialize};

use crate::model::pit_action::{PitAction, TireCorner};

/// Owner of the actions that are not a widget's. Never gated by the layout.
pub const APP_OWNER: &str = "app";

/// The per-widget show/hide action is generated by the frontend from its
/// widget catalog — the backend does not know the widgets — so it is
/// recognised by its shape: `widget:<type>:toggle-visibility`.
pub const WIDGET_VISIBILITY_ACTION_PREFIX: &str = "widget:";
pub const WIDGET_VISIBILITY_ACTION_SUFFIX: &str = ":toggle-visibility";

/// One press of a scroll key moves a block rather than a row — a key has no
/// inertia, so row-by-row stepping is too slow to be usable.
const SCROLL_STEP_ROWS: i32 = 3;

/// An input binding as it is stored and sent: a keyboard accelerator, or a
/// controller button addressed by the device's stable identity.
#[cfg_attr(feature = "dev", derive(specta::Type))]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq, Hash)]
#[serde(tag = "kind", rename_all = "camelCase")]
pub enum Binding {
    Keyboard {
        /// Tauri accelerator, e.g. "Control+Shift+P".
        accelerator: String,
    },
    Device {
        /// Stable device identity, not an enumeration index. See
        /// `input::identity`.
        #[serde(rename = "deviceId")]
        device_id: String,
        button: u32,
    },
}

/// `press` runs once, on key down. `hold` runs on both edges with whether the
/// key is down — interact mode's hold variant.
#[cfg_attr(feature = "dev", derive(specta::Type))]
#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum HotkeyTrigger {
    Press,
    Hold,
}

#[cfg_attr(feature = "dev", derive(specta::Type))]
#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub enum HotkeyKind {
    Sim,
    View,
    Settings,
}

/// A control message for the windows drawing a widget. Sent as a step, never a
/// value: only the window an instance is mounted in holds its state.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ViewControl {
    /// One class forward (`1`) or back (`-1`).
    StandingsClassStep(i32),
    StandingsScroll(i32),
    /// Positive lifts the chat towards older messages.
    StreamChatScroll(i32),
    /// Pops the order box up away from the pit lane.
    PitServiceToggle,
}

/// What an action does when its key fires.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum HotkeyEffect {
    Pit(PitAction),
    /// Hands the stop to the driver, or back to auto mode.
    PitAutoMode,
    View(ViewControl),
    ToggleDragMode,
    /// Toggles, or follows the key while held — `interactHotkeyMode` decides.
    InteractMode,
    /// Applied by the main window.
    Settings,
}

impl HotkeyEffect {
    pub const fn kind(self) -> HotkeyKind {
        match self {
            Self::Pit(_) | Self::PitAutoMode => HotkeyKind::Sim,
            Self::View(_) | Self::ToggleDragMode | Self::InteractMode => HotkeyKind::View,
            Self::Settings => HotkeyKind::Settings,
        }
    }

    pub const fn trigger(self) -> HotkeyTrigger {
        match self {
            Self::InteractMode => HotkeyTrigger::Hold,
            _ => HotkeyTrigger::Press,
        }
    }
}

/// One bindable action.
#[derive(Debug, Clone, Copy)]
pub struct HotkeyActionDecl {
    /// Stable, persisted key. Never renamed once shipped.
    pub id: &'static str,
    /// Widget type that owns the action, or [`APP_OWNER`]. Drives the layout
    /// gate and the grouping in the settings.
    pub owner: &'static str,
    /// i18n key under `bindings.actions` in `main-app.json`.
    pub label_key: &'static str,
    /// Shipped keyboard default; `None` starts unbound.
    pub default_key: Option<&'static str>,
    pub effect: HotkeyEffect,
}

const fn action(
    id: &'static str,
    owner: &'static str,
    label_key: &'static str,
    effect: HotkeyEffect,
) -> HotkeyActionDecl {
    HotkeyActionDecl {
        id,
        owner,
        label_key,
        default_key: None,
        effect,
    }
}

const fn bound(decl: HotkeyActionDecl, key: &'static str) -> HotkeyActionDecl {
    HotkeyActionDecl {
        default_key: Some(key),
        ..decl
    }
}

const fn pit(id: &'static str, label_key: &'static str, pit_action: PitAction) -> HotkeyActionDecl {
    action(id, "pit-service", label_key, HotkeyEffect::Pit(pit_action))
}

const fn tire(id: &'static str, label_key: &'static str, corner: TireCorner) -> HotkeyActionDecl {
    pit(id, label_key, PitAction::ToggleTire { corner })
}

/// Every action that does not depend on which widgets the build ships. The
/// per-widget visibility actions are generated beside these by the frontend.
pub const HOTKEY_ACTIONS: &[HotkeyActionDecl] = &[
    bound(
        action(
            "app:toggle-drag-mode",
            APP_OWNER,
            "toggleDragMode",
            HotkeyEffect::ToggleDragMode,
        ),
        "F9",
    ),
    bound(
        action(
            "app:toggle-interact-mode",
            APP_OWNER,
            "toggleInteractMode",
            HotkeyEffect::InteractMode,
        ),
        "F8",
    ),
    bound(
        action(
            "app:toggle-hide-all-widgets",
            APP_OWNER,
            "toggleHideAllWidgets",
            HotkeyEffect::Settings,
        ),
        "F10",
    ),
    action(
        "standings:cycle-view-mode",
        "standings",
        "standingsCycleViewMode",
        HotkeyEffect::Settings,
    ),
    action(
        "standings:class-prev",
        "standings",
        "standingsClassPrev",
        HotkeyEffect::View(ViewControl::StandingsClassStep(-1)),
    ),
    action(
        "standings:class-next",
        "standings",
        "standingsClassNext",
        HotkeyEffect::View(ViewControl::StandingsClassStep(1)),
    ),
    action(
        "standings:scroll-up",
        "standings",
        "standingsScrollUp",
        HotkeyEffect::View(ViewControl::StandingsScroll(-SCROLL_STEP_ROWS)),
    ),
    action(
        "standings:scroll-down",
        "standings",
        "standingsScrollDown",
        HotkeyEffect::View(ViewControl::StandingsScroll(SCROLL_STEP_ROWS)),
    ),
    // The chat counts back from the newest message, so up is the positive
    // direction — the opposite of the standings, which count down a list.
    action(
        "stream-chat:scroll-up",
        "stream-chat",
        "streamChatScrollUp",
        HotkeyEffect::View(ViewControl::StreamChatScroll(SCROLL_STEP_ROWS)),
    ),
    action(
        "stream-chat:scroll-down",
        "stream-chat",
        "streamChatScrollDown",
        HotkeyEffect::View(ViewControl::StreamChatScroll(-SCROLL_STEP_ROWS)),
    ),
    action(
        "delta:cycle-reference",
        "delta",
        "deltaCycleReference",
        HotkeyEffect::Settings,
    ),
    bound(
        action(
            "pit-service:toggle",
            "pit-service",
            "pitServiceToggle",
            HotkeyEffect::View(ViewControl::PitServiceToggle),
        ),
        "F7",
    ),
    // Auto mode itself is switched on by the auto fuel / auto tires settings;
    // this only decides who owns the stop happening right now.
    action(
        "pit-service:auto-mode",
        "pit-service",
        "pitServiceAutoMode",
        HotkeyEffect::PitAutoMode,
    ),
    pit(
        "pit-service:apply-order",
        "pitServiceApplyOrder",
        PitAction::ApplyPlanned,
    ),
    pit(
        "pit-service:clear-order",
        "pitServiceClearOrder",
        PitAction::Clear,
    ),
    pit("pit-service:fuel", "pitServiceFuel", PitAction::ToggleFuel),
    pit(
        "pit-service:fuel-plus",
        "pitServiceFuelPlus",
        PitAction::FuelStepUp,
    ),
    pit(
        "pit-service:fuel-minus",
        "pitServiceFuelMinus",
        PitAction::FuelStepDown,
    ),
    pit(
        "pit-service:tires-all",
        "pitServiceTiresAll",
        PitAction::ToggleAllTires,
    ),
    tire("pit-service:tire-lf", "pitServiceTireLf", TireCorner::Lf),
    tire("pit-service:tire-rf", "pitServiceTireRf", TireCorner::Rf),
    tire("pit-service:tire-lr", "pitServiceTireLr", TireCorner::Lr),
    tire("pit-service:tire-rr", "pitServiceTireRr", TireCorner::Rr),
    pit(
        "pit-service:tire-compound",
        "pitServiceTireCompound",
        PitAction::CycleCompound,
    ),
    pit(
        "pit-service:fast-repair",
        "pitServiceFastRepair",
        PitAction::ToggleFastRepair,
    ),
    pit(
        "pit-service:windshield",
        "pitServiceWindshield",
        PitAction::ToggleWindshield,
    ),
];

/// The declared action with this id.
pub fn find_action(id: &str) -> Option<&'static HotkeyActionDecl> {
    HOTKEY_ACTIONS.iter().find(|decl| decl.id == id)
}

/// The widget type a generated visibility action belongs to.
pub fn visibility_action_owner(id: &str) -> Option<&str> {
    id.strip_prefix(WIDGET_VISIBILITY_ACTION_PREFIX)?
        .strip_suffix(WIDGET_VISIBILITY_ACTION_SUFFIX)
        .filter(|owner| !owner.is_empty())
}

/// How the interact key behaves: a toggle, or on only while held.
#[cfg_attr(feature = "dev", derive(specta::Type))]
#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq, Default)]
#[serde(rename_all = "camelCase")]
pub enum InteractHotkeyMode {
    #[default]
    Toggle,
    Hold,
}

/// What the dispatcher needs from the main window's settings and layout,
/// pushed whenever any of it changes.
#[cfg_attr(feature = "dev", derive(specta::Type))]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Default)]
#[serde(rename_all = "camelCase")]
pub struct HotkeyContext {
    /// Widget types with at least one instance on screen in the live layout.
    /// A widget's actions fire only while it is listed here.
    pub widgets_on_screen: Vec<String>,
    pub interact_hotkey_mode: InteractHotkeyMode,
    /// Interact mode switches itself off after this long; 0 never does.
    pub interact_auto_off_seconds: f32,
}

/// The overlay's two mouse modes. Owned by the dispatcher, mirrored by every
/// window. Only one can be on: drag consumes pointer events on the container,
/// interact needs them to reach the widget content.
#[cfg_attr(feature = "dev", derive(specta::Type))]
#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq, Eq, Default)]
#[serde(rename_all = "camelCase")]
pub struct OverlayModes {
    pub drag_mode: bool,
    pub interact_mode: bool,
}

/// A settings action whose key fired, for the main window to apply.
#[cfg_attr(feature = "dev", derive(specta::Type))]
#[derive(Serialize, Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct HotkeySettingsAction {
    pub action_id: String,
}

/// An action as the settings window lists it.
#[cfg_attr(feature = "dev", derive(specta::Type))]
#[derive(Serialize, Debug, Clone, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct HotkeyActionSpec {
    pub id: String,
    pub owner: String,
    pub label_key: String,
    pub kind: HotkeyKind,
    pub trigger: HotkeyTrigger,
    pub default_binding: Option<Binding>,
}

impl From<&HotkeyActionDecl> for HotkeyActionSpec {
    fn from(decl: &HotkeyActionDecl) -> Self {
        Self {
            id: decl.id.to_string(),
            owner: decl.owner.to_string(),
            label_key: decl.label_key.to_string(),
            kind: decl.effect.kind(),
            trigger: decl.effect.trigger(),
            default_binding: decl.default_key.map(|key| Binding::Keyboard {
                accelerator: key.to_string(),
            }),
        }
    }
}

/// Writes the action list as a TypeScript value, next to the other generated
/// value files.
#[cfg(feature = "dev")]
pub fn export_hotkey_actions(path: &str) -> std::io::Result<()> {
    use crate::model::ts_values::GENERATED_HEADER;

    let specs: Vec<HotkeyActionSpec> = HOTKEY_ACTIONS.iter().map(HotkeyActionSpec::from).collect();
    let list = serde_json::to_string_pretty(&specs).map_err(std::io::Error::other)?;

    let out = format!(
        "{GENERATED_HEADER}\n\n\
         import type {{ HotkeyActionSpec }} from '@/types/bindings';\n\n\
         /** Every bindable action but the generated per-widget visibility ones. */\n\
         export const HOTKEY_ACTIONS: readonly HotkeyActionSpec[] = {list};\n\n\
         /** `widget:<type>:toggle-visibility` — see `model/hotkeys.rs`. */\n\
         export const WIDGET_VISIBILITY_ACTION_PREFIX = {WIDGET_VISIBILITY_ACTION_PREFIX:?};\n\n\
         export const WIDGET_VISIBILITY_ACTION_SUFFIX = {WIDGET_VISIBILITY_ACTION_SUFFIX:?};\n"
    );

    std::fs::write(path, out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_action_id_is_unique() {
        for (index, decl) in HOTKEY_ACTIONS.iter().enumerate() {
            assert!(
                HOTKEY_ACTIONS[index + 1..]
                    .iter()
                    .all(|other| other.id != decl.id),
                "duplicate action id {}",
                decl.id
            );
        }
    }

    #[test]
    fn only_the_interact_key_is_held() {
        let held: Vec<&str> = HOTKEY_ACTIONS
            .iter()
            .filter(|decl| decl.effect.trigger() == HotkeyTrigger::Hold)
            .map(|decl| decl.id)
            .collect();

        assert_eq!(held, vec!["app:toggle-interact-mode"]);
    }

    #[test]
    fn reads_the_widget_off_a_visibility_action() {
        assert_eq!(
            visibility_action_owner("widget:track-map:toggle-visibility"),
            Some("track-map")
        );
        assert_eq!(visibility_action_owner("widget::toggle-visibility"), None);
        assert_eq!(visibility_action_owner("standings:scroll-up"), None);
    }

    #[test]
    fn a_binding_reads_the_shape_the_settings_file_stores() {
        let device: Binding =
            serde_json::from_str(r#"{"kind":"device","deviceId":"guid-1","button":4}"#).unwrap();
        let keyboard: Binding =
            serde_json::from_str(r#"{"kind":"keyboard","accelerator":"F9"}"#).unwrap();

        assert_eq!(
            device,
            Binding::Device {
                device_id: "guid-1".into(),
                button: 4
            }
        );
        assert_eq!(
            keyboard,
            Binding::Keyboard {
                accelerator: "F9".into()
            }
        );
    }

    /// The checked-in list carries every id and label the backend declares.
    /// Quote-blind like the other value files: `oxfmt` rewrites the quotes.
    #[cfg(feature = "dev")]
    #[test]
    fn the_checked_in_action_list_is_current() {
        let checked_in = std::fs::read_to_string(crate::bindings::HOTKEY_ACTIONS_PATH)
            .expect("hotkey-actions.ts is missing — regenerate with UPDATE_BINDINGS=1")
            .replace('\'', "\"");

        for decl in HOTKEY_ACTIONS {
            for value in [Some(decl.id), Some(decl.label_key), decl.default_key]
                .into_iter()
                .flatten()
            {
                assert!(
                    checked_in.contains(&format!("\"{value}\"")),
                    "hotkey-actions.ts is stale: `{value}` is missing.\n\
                     Rerun with UPDATE_BINDINGS=1 cargo test --features dev, then npm run format."
                );
            }
        }
    }
}
