use pitwall::PitwallFrame;
use serde::{Deserialize, Serialize};
use specta::Type;

#[derive(PitwallFrame, Serialize, Deserialize, Type, Debug, Clone)]
pub struct TelemetryFrame {
    #[field_name = "Speed"]
    pub speed: f32,
    #[field_name = "RPM"]
    pub rpm: f32,
    #[field_name = "Gear"]
    pub gear: i32,
    #[field_name = "Throttle"]
    pub throttle: f32,
    #[field_name = "Brake"]
    pub brake: f32,
    #[field_name = "SteeringWheelAngle"]
    pub steering_wheel_angle: f32,
    #[field_name = "FuelLevel"]
    pub fuel_level: f32,
    #[field_name = "OilTemp"]
    pub oil_temp: f32,
    #[field_name = "WaterTemp"]
    pub water_temp: f32,
    #[field_name = "LapCurrentLapTime"]
    pub lap_current_lap_time: f32,
    #[field_name = "Clutch"]
    pub clutch: Option<f32>,
    #[field_name = "Lap"]
    pub lap: Option<i32>,
    #[field_name = "LapDist"]
    pub lap_dist: Option<f32>,
    #[field_name = "LapDistPct"]
    pub lap_dist_pct: Option<f32>,
    #[field_name = "LapLastLapTime"]
    pub lap_last_lap_time: Option<f32>,
    #[field_name = "LapBestLapTime"]
    pub lap_best_lap_time: Option<f32>,
    #[field_name = "SessionTime"]
    pub session_time: Option<f64>,
    #[field_name = "SessionTimeRemain"]
    pub session_time_remain: Option<f64>,
    #[field_name = "SessionState"]
    pub session_state: Option<i32>,
    #[field_name = "SessionFlags"]
    pub session_flags: Option<i32>,
    #[field_name = "SessionNum"]
    pub session_num: Option<i32>,
    #[field_name = "VelocityX"]
    pub velocity_x: Option<f32>,
    #[field_name = "VelocityY"]
    pub velocity_y: Option<f32>,
    #[field_name = "VelocityZ"]
    pub velocity_z: Option<f32>,
    #[field_name = "YawRate"]
    pub yaw_rate: Option<f32>,
    #[field_name = "Pitch"]
    pub pitch: Option<f32>,
    #[field_name = "Roll"]
    pub roll: Option<f32>,
    #[field_name = "LatAccel"]
    pub lat_accel: Option<f32>,
    #[field_name = "LongAccel"]
    pub long_accel: Option<f32>,
    #[field_name = "FuelLevelPct"]
    pub fuel_level_pct: Option<f32>,
    #[field_name = "FuelUsePerHour"]
    pub fuel_use_per_hour: Option<f32>,
    #[field_name = "OilPress"]
    pub oil_press: Option<f32>,
    #[field_name = "Voltage"]
    pub voltage: Option<f32>,
    #[field_name = "PlayerCarPosition"]
    pub player_car_position: Option<i32>,
    #[field_name = "PlayerCarClassPosition"]
    pub player_car_class_position: Option<i32>,
    #[field_name = "CarLeftRight"]
    pub car_left_right: Option<i32>,
    #[field_name = "OnPitRoad"]
    pub on_pit_road: Option<bool>,
    #[field_name = "IsOnTrack"]
    pub is_on_track: Option<bool>,
}
