// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
  async startTelemetryStream(): Promise<Result<null, string>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('start_telemetry_stream'),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
  async stopTelemetryStream(): Promise<Result<null, string>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('stop_telemetry_stream'),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: 'error', error: e as any };
    }
  },
};

/** user-defined events **/

export const events = __makeEvents__<{
  telemetryDebugEvent: TelemetryDebugEvent;
  telemetryDisconnectedEvent: TelemetryDisconnectedEvent;
  telemetryFrameEvent: TelemetryFrameEvent;
}>({
  telemetryDebugEvent: 'telemetry-debug-event',
  telemetryDisconnectedEvent: 'telemetry-disconnected-event',
  telemetryFrameEvent: 'telemetry-frame-event',
});

/** user-defined constants **/

/** user-defined types **/

export type TelemetryDebugEvent = string;
export type TelemetryDisconnectedEvent = null;
export type TelemetryFrame = {
  speed: number;
  rpm: number;
  gear: number;
  throttle: number;
  brake: number;
  steering_wheel_angle: number;
  fuel_level: number;
  oil_temp: number;
  water_temp: number;
  lap_current_lap_time: number;
  clutch: number | null;
  lap: number | null;
  lap_dist: number | null;
  lap_dist_pct: number | null;
  lap_last_lap_time: number | null;
  lap_best_lap_time: number | null;
  session_time: number | null;
  session_time_remain: number | null;
  session_state: number | null;
  session_flags: number | null;
  session_num: number | null;
  velocity_x: number | null;
  velocity_y: number | null;
  velocity_z: number | null;
  yaw_rate: number | null;
  pitch: number | null;
  roll: number | null;
  lat_accel: number | null;
  long_accel: number | null;
  fuel_level_pct: number | null;
  fuel_use_per_hour: number | null;
  oil_press: number | null;
  voltage: number | null;
  player_car_position: number | null;
  player_car_class_position: number | null;
  car_left_right: number | null;
  on_pit_road: boolean | null;
  is_on_track: boolean | null;
};
export type TelemetryFrameEvent = TelemetryFrame;

/** tauri-specta globals **/

import {
  invoke as TAURI_INVOKE,
  Channel as TAURI_CHANNEL,
} from '@tauri-apps/api/core';
import * as TAURI_API_EVENT from '@tauri-apps/api/event';
import { type WebviewWindow as __WebviewWindow__ } from '@tauri-apps/api/webviewWindow';

type __EventObj__<T> = {
  listen: (
    cb: TAURI_API_EVENT.EventCallback<T>
  ) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
  once: (
    cb: TAURI_API_EVENT.EventCallback<T>
  ) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
  emit: null extends T
    ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
    : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
  | { status: 'ok'; data: T }
  | { status: 'error'; error: E };

function __makeEvents__<T extends Record<string, any>>(
  mappings: Record<keyof T, string>
) {
  return new Proxy(
    {} as unknown as {
      [K in keyof T]: __EventObj__<T[K]> & {
        (handle: __WebviewWindow__): __EventObj__<T[K]>;
      };
    },
    {
      get: (_, event) => {
        const name = mappings[event as keyof T];

        return new Proxy((() => {}) as any, {
          apply: (_, __, [window]: [__WebviewWindow__]) => ({
            listen: (arg: any) => window.listen(name, arg),
            once: (arg: any) => window.once(name, arg),
            emit: (arg: any) => window.emit(name, arg),
          }),
          get: (_, command: keyof __EventObj__<any>) => {
            switch (command) {
              case 'listen':
                return (arg: any) => TAURI_API_EVENT.listen(name, arg);
              case 'once':
                return (arg: any) => TAURI_API_EVENT.once(name, arg);
              case 'emit':
                return (arg: any) => TAURI_API_EVENT.emit(name, arg);
            }
          },
        });
      },
    }
  );
}
