import type { WidgetManifest } from '@/types/widget-settings';
import {
  COMMON_WIDGET_DEFAULTS,
  TRANSPARENT_APPEARANCE_DEFAULTS,
} from '@ui/widgets/widget-manifest';

export const DUEL_BAR_MANIFEST: WidgetManifest = {
  id: 'duel-bar',
  telemetryEvents: ['proximity', 'relative', 'driverEntries'],
  label: 'Duel Bar',
  description: 'Who is fighting you right now, on a vertical distance axis.',
  requiredCapabilities: ['radar'],
  designWidth: 440,
  designHeight: 420,
  overflowVisible: true,
  userSettings: {
    enabled: false,
    x: 200,
    y: 200,
    currentWidth: 440,
    currentHeight: 420,
    ...COMMON_WIDGET_DEFAULTS,
    ...TRANSPARENT_APPEARANCE_DEFAULTS,
    trigger: 'gap',
    gapThreshold: 2,
    distanceThreshold: 50,
    hideDelay: 3,
    sides: 'both',
    maxRows: 2,
    showTicks: true,
    showTickLabels: true,
    compactMode: false,
    showDistance: true,
    nameMode: 'initial',
    mergeOverlapping: true,
    mergeDistance: 2,
    hideInPits: true,
    qualifyingVisibility: 'auto',
    plateOpacity: 1,
    showClassBadge: true,
    scaleByDistance: true,
    otherClass: 'dim',
    glowRange: 30,
    raceOnly: true,
  },
};
